<?php
namespace com\cminds\tableofcontents\settings;

const TYPE_BOOL          = 'bool';
const TYPE_INT           = 'int';
const TYPE_STRING        = 'string';
const TYPE_TEXTAREA      = 'textarea';
const TYPE_RICH_TEXT     = 'rich_text';
const TYPE_RADIO         = 'radio';
const TYPE_SELECT        = 'select';
const TYPE_MULTISELECT   = 'multiselect';
const TYPE_MULTICHECKBOX = 'multicheckbox';
const TYPE_LABEL         = 'label';
const TYPE_CUSTOM        = 'custom';
const TYPE_COLOR         = 'color';


$config = [
    'abbrev'  => 'cmtoc', // *Plugin prefix which used as prefix for plugin options names (slugs), example cmicca, cma, cmed etc
    'tabs'    => [
        0 => [
        	'tab_name' => 'General Settings',
	        'section' => [
	        	0 => 'Display Settings',
                1 => 'Performance & Debug',
	        ]
        ],
        1 => [
            'tab_name' => 'Table of Contents',
            'section' => [
                0 => 'General Settings',
                1 => 'Title style',
                2 => 'Default appearance',
                3 => 'Back to the Top Button',
                4 => 'General Styling',
                5 => 'Element Selector',
                6 => 'Floating TOC',
                7 => 'Sticky widget settings',
                8 => 'Custom CSS',
                9 => 'Elements Styling',
            ]
        ],
    ],
    'value'  => [
    ],
    'settings' => [
	    'cmtoc_table_of_contentsOnPosttypes' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 0,
		    'label'       => __( 'Display table-of-contents on given post types:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select the custom post types where you\'d like the Table of Contents Terms to be highlighted.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsOnlySingle' => [
		    'type'        => TYPE_BOOL,
		    'value'       => false,
		    'tab'         => 0,
		    'section'     => 0,
		    'label'       => __( 'Only show CM Table Of Contents Pro on single posts/pages (not Homepage, authors etc.)?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you wish to only highlight CM Table Of Contents Pro when viewing a single page/post.
                            This can be used so Tables of Content aren\'t displayed on your homepage, or author pages and other taxonomy related pages.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_content_disable_for_page_option' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 0,
		    'label'       => __( 'Display TOC on all chosen post types:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'If enabled, TOC will be shown on each post/page, where parser found matching items.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_content_auto_shortcode_disable_option' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 0,
		    'label'       => __( 'Disable automatic adding TOC at the top of content:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'If enabled, TOC won\'t be automatically displayed at the top of the content. TOC will be displayed only if you insert a shortcode [cmtoc_table_of_contents]. The shortcode can be insterted in any custom place within the post/page.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_acf_fields_to_exclude' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 0,
		    'label'       => __( 'ACF Fields to exclude from TOC Parser:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Enter slugs of the ACF fields separated by a comma and without spaces. Those fields will be excluded from TOC parses, so they will not appear in the TOC', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsMinNumHead' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 0,
		    'options'     => [ '1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6, '7' => 7, '8' => 8, '9' => 9, '10' => 10 ],
		    'label'       => __( 'Minimum number of headings to display TOC:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Choose the minimum amount of heading on the page.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_titles_to_exclude' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 0,
		    'label'       => __( 'Titles to exclude from TOC Parser:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Enter titles separated by a comma and without spaces. Those titles will be excluded from TOC parses, so they will not appear in the TOC', 'cm-table-of-content-table-of-content' ),
	    ],
		'cmtoc_AddWizardMenu'           => [
            'type'        => TYPE_BOOL,
            'value'       => 1,
            'tab'         => 0,
            'section'     => 0,
            'label'       => __('Display "Setup Wizard" in plugin menu', 'cmf'),
            'description' => __('Uncheck this to remove Setup Wizard from plugin menu.', 'cmf'),
        ],
        'cmtoc_script_in_footer' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 1,
		    'label'       => __( 'Load the scripts in footer?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '<strong>Warning: Don\'t change this setting unless you know what you\'re doing</strong> 
                                Select this option if you want to load the plugin\'s js files in the footer.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentEnableCaching' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 1,
		    'label'       => __( 'Enable the caching mechanisms', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to use the internal caching mechanisms.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsNoFollow' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 1,
		    'label'       => __( 'No follow', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'rel="nofollow" will be added to TOC links.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsGoogleOff' => [
		    'type'        => TYPE_CUSTOM,
		    'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 0,
		    'section'     => 1,
		    'label'       => __( 'Embed googleon/googleoff tags', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Prevent Table Of Contents from being indexed by using googleoff/googleon tags', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsListType' => [
		    'type'        => TYPE_SELECT,
		    'value'       => 'none',
		    'tab'         => 1,
		    'section'     => 0,
            'options'     => [ 'none' => 'None', 'circle' => 'Circle', 'square' => 'Square', 'decimal' => 'Numbers', 'decimal-indent' => 'Nested numbers', 'upper-roman' => 'Upper Roman', 'lower-roman' => 'Lower Roman', 'upper-alpha' => 'Upper Alphabet', 'lower-alpha' => 'Lower Alphabet' ],
            'label'       => __( 'List type:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the list elements of the Table of Contents.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_row_toggle' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
		    'label'       => __( 'Allow to toggle row visibility?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to allow to toggle the visibility of the single TOC rows.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_structuredAnchors' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
		    'label'       => __( 'Use title-based structured anchors?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to use anchors based on term titles eg. "#example-title" for "Example Title" instead of "#cmtoc_anchor_0".', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_includeFamilyElements' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
		    'label'       => __( 'Include the pages parent/child elements in the TOC by default?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to include the pages "children" and parent in Table of Content. Allows to create Table of Contents spanning multiple pages as long as they\'re connected to each other.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_filterClass' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
		    'label'       => __( 'Exclude headings from element with class?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Exclude the headings in the HTML container having this class.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsOffset' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
		    'label'       => __( 'Jump vertical offset[px]:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'You can change this value if you notice that the site jumps too close/too far after clicking on the anchor. Increase if the jump is too far, decrease if it\'s too close. (value in pixels)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsOffsetMobile' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 0,
            'label'       => __( 'Jump vertical offset[px] (for mobile devices):', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'You can change this value if you notice that the site jumps too close/too far after clicking on the anchor. Increase if the jump is too far, decrease if it\'s too close. (value in pixels)', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsWrapping' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
            'label'       => __( 'Wrapping:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select how to show TOC: left aligned, right aligned with text wrapped or no text wrapping. Note that the wrapping will not work if the element after the TOC has the parameter "position:relative" or "position:absolute". Learn more about the position property in CSS.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_into_two_columns' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 0,
		    'label'       => __( 'Show Table of Contents into two columns:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'The Table of Contents will be splitted into two columns. If this option enabled the "Wrapping" option will be disabled and set to None', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_sticky_widget_expand_collapse_subtitles' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 0,
            'label'       => __( 'Auto expand/collapse sub-chapters', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Use auto expand/collapse sub-chapters for sticky widget and floating TOC', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_highlight_active_title' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 0,
            'label'       => __( 'Highlight active title', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'If this option is enabled, the Table of Contents will display the active title(s)', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_toc_active_title_custom_css' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 0,
            'label'       => __( 'Active title custom CSS', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Add your own style for the active title.', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsHeaderDescription' => [
            'type'        => TYPE_LABEL,
            'value'       => 'Table Of Contents',
            'tab'         => 1,
            'section'     => 1,
            'label'       => __( 'Title text:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the label of TOC title', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_header_show_label' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 1,
            'label'       => __( 'Show label:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the label of the "show" link to expand the Table of Contents from collapsed state.', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_header_hide_label' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 1,
            'label'       => __( 'Hide label:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the label of the "hide" link to collapse the Table of Contents from expanded state.', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_header_alignment' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Title text alignment:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select title text alignment.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_header_label_alignment' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Show/hide label alignment:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select "show/hide" label position.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsShowHideStyling_separator' => [
            'type'        => TYPE_CUSTOM,
            'value'       => '',
            'tab'         => 1,
            'section'     => 1,
            'html'        => '',
            'label'       => __( 'Show/hide toggle styling:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the style of the "Show/hide" link', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsShowHideSize' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the "Show/hide" link', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsShowHideColor' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the "Show/hide" link', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsShowHideWeight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the "Show/hide" link', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsShowHideDecoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the "Show/hide" link', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsShowHideStyle' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 1,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the "Show/hide" link', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_fold' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 2,
		    'label'       => __( 'Collapse table of contents by default?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to hide the content of the Table of Contents on the page load. It will only be displayed after clicking the "Show/hide" button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsMobileFold' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 2,
		    'label'       => __( 'Always hide content by default on devices with screen width less than:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'On the smaller screens the Table of Content will be folded by default even when the <strong> Hide the content of the Table of Contents by default? </strong> is unchecked.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_scroll_time' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 2,
		    'label'       => __( 'Smooth scrolling:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set time in ms for scroll: when TOC item clicked, page will smoothly scroll to linked subtitle. If set to zero, it will promptly jump to target', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_jump_back_to_top' => [
		    'type'        => TYPE_BOOL,
		    'value'       => false,
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Show button', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to show the button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_jump_back_to_top_position' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Button takes users to', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select the position where the button needs to take users to.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_background' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#fff',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Background Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Choose background color.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_border_width' => [
		    'type'        => TYPE_STRING,
		    'value'       => '1px',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Border width:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the width of the border of the button. Leave empty to remove the border.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_border_color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#cecece',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Border color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the color of the border of the button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_right_space' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Space between the button and the right border of the window:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the width of space between the button and the right border of the window(in pixels).', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_bottom_space' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Space between the button and the bottom of the window:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the width of space between the button and the bottom of the window(in pixels).', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_jump_back_to_top_text' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Text:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the label of button title.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_text_size' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Text Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the size of the button label text.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_text_color' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Text Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Choose button text color.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_arrow_size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '40px',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Arrow Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the size of the arrow(in pixels).', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_back_to_top_arrow_color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#111',
		    'tab'         => 1,
		    'section'     => 3,
		    'label'       => __( 'Arrow Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Choose arrow color.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsBackgroundColor' => [
            'type'        => TYPE_COLOR,
            'value'       => '#fff',
            'tab'         => 1,
            'section'     => 4,
            'label'       => __( 'Background color:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the background color of the Table of Contents.', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsCurrentElementCustomStyle' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 4,
		    'label'       => __( 'Style the current element differently?', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to style the current(selected/clicked) element of the Table of Contents differently.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsCurrentElement_separator' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => '',
		    'tab'         => 1,
		    'section'     => 4,
		    'label'       => __( 'Current element styling:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsCurrentElementColor' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 4,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsCurrentElementWeight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 4,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsCurrentElementDecoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 4,
            'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsCurrentElementStyle' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 4,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsBorder_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 4,
		    'html'     => '',
		    'label'       => __( 'Border styling:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the border of the Table of Contents.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsBorderWidth' => [
		    'type'        => TYPE_STRING,
		    'value'       => '0px',
		    'tab'         => 1,
		    'section'     => 4,
		    'options'     => [ 'session' => 'Duration of session', 'view' => 'Single view' ],
		    'label'       => __( 'Border width:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the border of the Table of Contents.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsBorderColor' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 4,
		    'options'     => [ 'session' => 'Duration of session', 'view' => 'Single view' ],
		    'label'       => __( 'Border color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of the border of the Table of Contents.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
            'html'        => '',
		    'label'       => __( 'Level 0:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the selector attributes for the 0-level table of content elements. Defaults to: h1', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Tag' => [
		    'type'        => TYPE_STRING,
		    'value'       => 'h1',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Tag:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Class' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Class:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Id' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Id:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1_separator' => [
            'type'        => TYPE_CUSTOM,
            'value'       => '',
            'tab'         => 1,
            'section'     => 5,
            'html'        => '',
            'label'       => __( 'Level 1:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the selector attributes for the 1-level table of content elements. Defaults to: h2', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsLevel1Tag' => [
		    'type'        => TYPE_STRING,
		    'value'       => 'h2',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Tag:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Class' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Class:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Id' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Id:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2_separator' => [
            'type'        => TYPE_CUSTOM,
            'value'       => '',
            'tab'         => 1,
            'section'     => 5,
            'html'        => '',
            'label'       => __( 'Level 2:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the selector attributes for the 2-level table of content elements. Defaults to: h3', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsLevel2Tag' => [
		    'type'        => TYPE_STRING,
		    'value'       => 'h3',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Tag:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Class' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Class:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Id' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Id:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3_separator' => [
            'type'        => TYPE_CUSTOM,
            'value'       => '',
            'tab'         => 1,
            'section'     => 5,
            'html'        => '',
            'label'       => __( 'Level 3:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the selector attributes for the 3-level table of content elements. Defaults to: h4', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsLevel3Tag' => [
		    'type'        => TYPE_STRING,
		    'value'       => 'h4',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Tag:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Class' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Class:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Id' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Id:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4_separator' => [
            'type'        => TYPE_CUSTOM,
            'value'       => '',
            'tab'         => 1,
            'section'     => 5,
            'html'        => '',
            'label'       => __( 'Level 4:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the selector attributes for the 4-level table of content elements. Defaults to: h5', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsLevel4Tag' => [
		    'type'        => TYPE_STRING,
		    'value'       => 'h5',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Tag:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Class' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Class:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Id' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Id:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5_separator' => [
            'type'        => TYPE_CUSTOM,
            'value'       => '',
            'tab'         => 1,
            'section'     => 5,
            'html'        => '',
            'label'       => __( 'Level 5:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the selector attributes for the 5-level table of content elements. Defaults to: h6', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_table_of_contentsLevel5Tag' => [
		    'type'        => TYPE_STRING,
		    'value'       => 'h6',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Tag:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Class' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Class:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Id' => [
		    'type'        => TYPE_STRING,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 5,
		    'label'       => __( 'Id:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_button' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Show button', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to show the button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_fb_show_in_content_area' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Render button in content area', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'The TOC button will appear only when the article/post content is visible on screen during scrolling. When the content is out of screen, the  button will disappear.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_button_hide_main' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Hide main TOC', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Select this option if you want to hide the main Table of Contents and display only floating one. Can only work if  "Render button in content area" is enabled', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_button_text' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Button Text:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the label of button title.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_btn_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '#fff',
		    'tab'         => 1,
		    'section'     => 6,
            'html'        => '',
		    'label'       => __( 'Button styling:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_btn_background' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Background color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_btn_color' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Text color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_btn_opacity' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
            'label'       => __( 'Opacity:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_btn_border_color' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Border color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_btn_border_width' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Border width:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC button.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 6,
            'html'        => '',
		    'label'       => __( 'Table of contents styling:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_font_size' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Text font-size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_font_color' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Text color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_bg_color' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Background color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_opacity' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Background opacity:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_border_width' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Border width:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_border_color' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Border color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_height' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Content height:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_floating_content_position' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 6,
		    'label'       => __( 'Contents position:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of floating TOC.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_sticky_widget_title_label' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 7,
            'label'       => __( 'Title for sticky widget', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Label for title for sticky widget', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_sticky_widget_border_color' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 7,
            'label'       => __( 'Sticky widget border color:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the style of sticky widget border color:', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_sticky_widget_border_width' => [
            'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
            'tab'         => 1,
            'section'     => 7,
            'label'       => __( 'Border width for the sticky widget:', 'cm-table-of-content-table-of-content' ),
            'description' => __( 'Set the width for the sticky widget. Leave empty to remove the border.', 'cm-table-of-content-table-of-content' ),
        ],
        'cmtoc_custom_css_field' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 8,
		    'label'       => __( 'Custom CSS', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Place your styles here to override any CSS rule of the plugin.', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel_0_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 9,
		    'html'        => '',
		    'label'       => __( 'Level 0:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '25px',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Weight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Decoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel0Style' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel_1_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 9,
		    'html'        => '',
		    'label'       => __( 'Level 1:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '22px',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Weight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Decoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel1Style' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel_2_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 9,
		    'html'        => '',
		    'label'       => __( 'Level 2:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '19px',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Weight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Decoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel2Style' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel_3_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 9,
		    'html'        => '',
		    'label'       => __( 'Level 3:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '16px',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Weight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Decoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel3Style' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel_4_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 9,
		    'html'        => '',
		    'label'       => __( 'Level 4:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '25px',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Weight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Decoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel4Style' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel_5_separator' => [
		    'type'        => TYPE_CUSTOM,
		    'value'       => '',
		    'tab'         => 1,
		    'section'     => 9,
		    'html'        => '',
		    'label'       => __( 'Level 5:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( 'Set the style of table-of-content title (if set)', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Size' => [
		    'type'        => TYPE_STRING,
		    'value'       => '13px',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Size:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Color' => [
		    'type'        => TYPE_COLOR,
		    'value'       => '#373737',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Color:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Weight' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Weight:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Decoration' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Decoration:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
        'cmtoc_table_of_contentsLevel5Style' => [
		    'type'        => TYPE_CUSTOM,
			'html'        => 'Available in Pro version and above. <a href="'.admin_url('admin.php?page=cmtoc_pro').'" target="">UPGRADE NOW&nbsp;➤</a>',
		    'tab'         => 1,
		    'section'     => 9,
		    'label'       => __( 'Style:', 'cm-table-of-content-table-of-content' ),
		    'description' => __( '', 'cm-table-of-content-table-of-content' ),
	    ],
    ],
    'presets' => [
        'default' => [
            0  => [                 // should be copied for each tab. index should be equal to tab index
	            'generic' => [
		            'label'    => '',
		            'before'   => '',
		            'settings' => [

		            ]
	            ],
            ],
        ]
    ]

];
